<a href="https://colab.research.google.com/github/JialongYin/Deep-learning-practice/blob/master/IDIAP%20EE559%20Deep%20Learning/EE559_%E2%80%93_Practical_Session_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **EE559 – Practical Session 1**

**Introduction**

The objective of this session is to practice with basic tensor manipulations in pytorch, to understand the relation between a tensor and its underlying storage, and get a sense of the efficiency of tensor-based computation compared to their equivalent python iterative implementations.


In [0]:
import torch,time

In [44]:
print('# 1 #')
mat = torch.full((13,13),1,dtype=torch.int8)
mat[:,(1,6,11)] = 2
mat[(1,6,11),:] = 2
mat[3:5,3:5] = 3
mat[3:5,8:10] = 3
mat[8:10,3:5] = 3
mat[8:10,8:10] = 3
print(mat)

# 1 #


tensor([[1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 3, 3, 1, 2, 1, 3, 3, 1, 2, 1],
        [1, 2, 1, 3, 3, 1, 2, 1, 3, 3, 1, 2, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 3, 3, 1, 2, 1, 3, 3, 1, 2, 1],
        [1, 2, 1, 3, 3, 1, 2, 1, 3, 3, 1, 2, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1]], dtype=torch.int8)

In [51]:
print('# 2 #')
mat = torch.empty((20,20)).normal_()
diag = torch.diag(torch.arange(1., 21.))
eig,_ = torch.eig(torch.mm(torch.mm(torch.inverse(mat), diag),mat))
print(eig[:,0].sort()[0])

# 2 #


tensor([ 1.0000,  2.0000,  3.0000,  4.0000,  5.0000,  6.0000,  7.0000,  8.0000,
         9.0000, 10.0000, 11.0000, 12.0000, 13.0000, 14.0000, 15.0000, 16.0000,
        17.0000, 18.0000, 19.0001, 20.0000])

In [55]:
print('# 3 #')
mat1 = torch.empty((5000,5000)).normal_()
mat2 = torch.empty((5000,5000)).normal_()
t_start = time.perf_counter()
prod = mat1.mm(mat2)
t_stop = time.perf_counter()
print(t_stop-t_start)


# 3 #
3.672334509000393


In [65]:
print('# 4 #')
def mul_row(m):
  mat = torch.empty(m.size(0),m.size(1))
  for i in range(mat.size(0)):
    for j in range(mat.size(1)):
      mat[i][j] = m[i][j]*(i+1)
  return mat
def mul_row_fast(m):
  arr = torch.arange(1,m.size(0)+1).float().view(-1,1)
  mat = torch.mul(m, arr)
  return mat
m = torch.full((1000, 400), 2.0)
t1_start = time.perf_counter()
print(mul_row(m))
t1_stop = time.perf_counter()
t2_start = time.perf_counter()
print(mul_row_fast(m))
t2_stop = time.perf_counter()
print(t1_stop-t1_start)
print(t2_stop-t2_start)

# 4 #
tensor([[   2.,    2.,    2.,  ...,    2.,    2.,    2.],
        [   4.,    4.,    4.,  ...,    4.,    4.,    4.],
        [   6.,    6.,    6.,  ...,    6.,    6.,    6.],
        ...,
        [1996., 1996., 1996.,  ..., 1996., 1996., 1996.],
        [1998., 1998., 1998.,  ..., 1998., 1998., 1998.],
        [2000., 2000., 2000.,  ..., 2000., 2000., 2000.]])
tensor([[   2.,    2.,    2.,  ...,    2.,    2.,    2.],
        [   4.,    4.,    4.,  ...,    4.,    4.,    4.],
        [   6.,    6.,    6.,  ...,    6.,    6.,    6.],
        ...,
        [1996., 1996., 1996.,  ..., 1996., 1996., 1996.],
        [1998., 1998., 1998.,  ..., 1998., 1998., 1998.],
        [2000., 2000., 2000.,  ..., 2000., 2000., 2000.]])
6.949604011999327
0.0022917060014151502
